'use strict';
const fs=require('fs'),path=require('path');
const clean=(v,m=500)=>String(v==null?'':v).trim().slice(0,m);
const num=v=>{const n=Number(v);return Number.isFinite(n)?n:null};
const configured=e=>Boolean(e.FLINKS_API_BASE&&e.FLINKS_IFRAME_URL&&e.FLINKS_AUTH_KEY&&e.FLINKS_API_KEY);
const envName=e=>/toolbox|sandbox/i.test(String(e.FLINKS_API_BASE||e.FLINKS_IFRAME_URL||''))?'sandbox':'production';
function dbShape(s={}){return{connections:Array.isArray(s.connections)?s.connections:[],accounts:Array.isArray(s.accounts)?s.accounts:[],transactions:Array.isArray(s.transactions)?s.transactions:[]}}
async function parse(r){const raw=await r.text();let d={};try{d=raw?JSON.parse(raw):{}}catch{}if(!r.ok&&r.status!==202){const e=new Error(clean(d?.Message||d?.message||raw||('Flinks request failed ('+r.status+').'),350));e.status=r.status;throw e}return{status:r.status,data:d}}
module.exports=function createFlinksFinance({env=process.env,dataDir='/data'}={}){
 const file=path.join(dataDir,'finance-flinks.json'),base=()=>clean(env.FLINKS_API_BASE,500).replace(/\/$/,'');
 const load=()=>{try{return dbShape(JSON.parse(fs.readFileSync(file,'utf8')))}catch{return dbShape()}};
 const save=db=>{fs.mkdirSync(dataDir,{recursive:true});const t=file+'.tmp';fs.writeFileSync(t,JSON.stringify(dbShape(db),null,2));fs.renameSync(t,file)};
 async function authToken(){const r=await fetch(base()+'/GenerateAuthorizeToken',{method:'POST',headers:{'Content-Type':'application/json','flinks-auth-key':env.FLINKS_AUTH_KEY}});const x=await parse(r);return clean(x.data?.AuthorizeToken||x.data?.authorizeToken||x.data?.Token||x.data?.token,4000)}
 async function authorize(loginId,mostRecentCached=true){const token=await authToken();const r=await fetch(base()+'/Authorize',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({LoginId:loginId,MostRecentCached:mostRecentCached,Save:true,AuthorizeToken:token})});const x=await parse(r);if(x.status===203){const e=new Error('This bank requires authentication before Flinks can refresh it.');e.status=203;e.userActionRequired=true;throw e}const requestId=clean(x.data?.RequestId||x.data?.requestId,200);if(!requestId)throw new Error('Flinks did not return a requestId.');return requestId}
 async function detail(requestId){let r=await fetch(base()+'/GetAccountsDetail',{method:'POST',headers:{'Content-Type':'application/json','x-api-key':env.FLINKS_API_KEY},body:JSON.stringify({RequestId:requestId})});let x=await parse(r);if(x.status===202){for(let i=0;i<12;i++){await new Promise(res=>setTimeout(res,2500));r=await fetch(base()+'/GetAccountsDetailAsync?requestId='+encodeURIComponent(requestId),{headers:{'x-api-key':env.FLINKS_API_KEY}});x=await parse(r);if(x.status!==202)break}}if(x.status===202){const e=new Error('Flinks is still processing this account. Try Sync again shortly.');e.status=202;throw e}return x.data}
 function map(loginId,payload){const institution=clean(payload?.Institution||payload?.institution||'Flinks connection',180),institutionId=clean(payload?.InstitutionId||payload?.institutionId,100),now=new Date().toISOString(),accounts=[],transactions=[];
  for(const a of Array.isArray(payload?.Accounts)?payload.Accounts:[]){
   const aid=clean(a?.Id||a?.id,160),item='flinks:'+loginId,curr=clean(a?.Currency||a?.currency||'CAD',10).toUpperCase();
   accounts.push({accountId:'flinks:'+aid,itemId:item,name:clean(a?.Title||a?.Name||a?.AccountType||'Account',180),officialName:clean(a?.Title||'',180),mask:clean(a?.AccountNumber||'',80).replace(/\D/g,'').slice(-4),type:'depository',subtype:clean(a?.AccountType||a?.Category||'',100).toLowerCase(),currency:curr,currentBalance:num(a?.Balance?.Current??a?.Balance?.Available??a?.Balance),availableBalance:num(a?.Balance?.Available??a?.AvailableBalance),creditLimit:num(a?.Balance?.Limit??a?.CreditLimit),updatedAt:now});
   for(const t of Array.isArray(a?.Transactions)?a.Transactions:[]){const debit=num(t?.Debit)||0,credit=num(t?.Credit)||0;transactions.push({transactionId:'flinks:'+clean(t?.Id||[aid,t?.Date,t?.Description,debit,credit].join('|'),220),itemId:item,accountId:'flinks:'+aid,name:clean(t?.Description||'Transaction',220),merchantName:clean(t?.MerchantName||'',180),amount:debit>0?debit:-Math.abs(credit),currency:curr,date:clean(t?.Date,30).slice(0,10),authorizedDate:'',pending:false,categoryPrimary:clean(t?.Category||'OTHER',100).toUpperCase().replace(/[^A-Z0-9]+/g,'_'),categoryDetailed:clean(t?.Category||'',120),paymentChannel:'',website:'',logoUrl:''})}
  }
  return{connection:{itemId:'flinks:'+loginId,loginId,institutionId,institutionName:institution,status:'connected',error:'',lastSyncedAt:clean(payload?.Login?.LastRefresh,80)||now,connectedAt:now,provider:'flinks',providerName:'Flinks'},accounts,transactions}
 }
 async function syncOne(loginId){const requestId=await authorize(loginId,true),payload=await detail(requestId),mapped=map(loginId,payload),db=load(),prev=db.connections.find(x=>x.loginId===loginId);mapped.connection.connectedAt=prev?.connectedAt||mapped.connection.connectedAt;db.connections=db.connections.filter(x=>x.loginId!==loginId).concat(mapped.connection);db.accounts=db.accounts.filter(x=>x.itemId!=='flinks:'+loginId).concat(mapped.accounts);db.transactions=db.transactions.filter(x=>x.itemId!=='flinks:'+loginId).concat(mapped.transactions);save(db)}
 return{
  configured:()=>configured(env),environment:()=>envName(env),
  async start(itemId=''){if(!configured(env)){const e=new Error('Flinks is not configured for Quest Log.');e.status=503;throw e}const token=await authToken(),loginId=clean(itemId,200).replace(/^flinks:/,'');const u=new URL(env.FLINKS_IFRAME_URL);u.searchParams.set('authorizeToken',token);u.searchParams.set('redirectUrl',clean(env.FLINKS_REDIRECT_URL||'',500)||'about:blank');u.searchParams.set('accountSelectorEnable','true');if(loginId){u.searchParams.set('loginId',loginId);u.searchParams.set('reconnect','true')}return{provider:'flinks',launch:'iframe',url:u.toString()}},
  async complete(loginId,institution=''){const id=clean(loginId,200);if(!id){const e=new Error('Flinks loginId is required.');e.status=400;throw e}const db=load();if(!db.connections.some(x=>x.loginId===id))db.connections.push({itemId:'flinks:'+id,loginId:id,institutionName:clean(institution,180)||'Flinks connection',status:'syncing',error:'',connectedAt:new Date().toISOString(),provider:'flinks',providerName:'Flinks'});save(db);await syncOne(id);return this.summary(false)},
  async sync(){const errors=[];for(const connection of load().connections){try{await syncOne(connection.loginId)}catch(e){const db=load(),row=db.connections.find(x=>x.loginId===connection.loginId);if(row){row.status=e.userActionRequired||e.status===203?'user_action_required':'error';row.error=clean(e.message,300);save(db)}errors.push({itemId:connection.itemId,provider:'flinks',error:clean(e.message,300)})}}return errors},
  async disconnect(itemId){const id=clean(itemId,200).replace(/^flinks:/,''),db=load();db.connections=db.connections.filter(x=>x.loginId!==id);db.accounts=db.accounts.filter(x=>x.itemId!=='flinks:'+id);db.transactions=db.transactions.filter(x=>x.itemId!=='flinks:'+id);save(db);return{ok:true}},
  async summary(sync=true){const errors=configured(env)&&sync?await this.sync():[],db=load(),connections=db.connections.map(x=>({...x,provider:'flinks',providerName:'Flinks'}));return{configured:configured(env),provider:'Flinks',environment:envName(env),connections,accounts:db.accounts.map(x=>({...x,provider:'flinks'})),transactions:db.transactions.map(x=>({...x,provider:'flinks'})).sort((a,b)=>String(b.date||'').localeCompare(String(a.date||''))).slice(0,1500),errors,lastSyncedAt:connections.map(x=>x.lastSyncedAt).filter(Boolean).sort().at(-1)||null}}
 }
};