import { resolveQuestLogUser } from './users.js';
const clean=(v,m=500)=>String(v==null?'':v).trim().slice(0,m);
const num=v=>{const n=Number(v);return Number.isFinite(n)?n:null};
const flinksConfigured=e=>Boolean(e.FLINKS_API_BASE&&e.FLINKS_IFRAME_URL&&e.FLINKS_AUTH_KEY&&e.FLINKS_API_KEY);
const yodleeConfigured=e=>Boolean(e.YODLEE_CLIENT_ID&&e.YODLEE_SECRET&&e.YODLEE_FASTLINK_URL&&e.YODLEE_FASTLINK_CONFIG_NAME);
const yBase=e=>clean(e.YODLEE_API_URL||'https://sandbox.api.yodlee.com/ysl',500).replace(/\/$/,'');
const fBase=e=>clean(e.FLINKS_API_BASE,500).replace(/\/$/,'');
async function ensure(env){await env.DB.prepare(`CREATE TABLE IF NOT EXISTS finance_external_provider_state(user_key TEXT NOT NULL,provider TEXT NOT NULL,state_json TEXT NOT NULL DEFAULT '{}',updated_at TEXT NOT NULL DEFAULT (datetime('now')),PRIMARY KEY(user_key,provider))`).run()}
async function userKey(env,identity){return (await resolveQuestLogUser(env,identity)).userId}
async function getState(env,key,provider){await ensure(env);const r=await env.DB.prepare('SELECT state_json FROM finance_external_provider_state WHERE user_key=? AND provider=?').bind(key,provider).first();try{return JSON.parse(r?.state_json||'{}')}catch{return{}}}
async function putState(env,key,provider,state){await ensure(env);await env.DB.prepare(`INSERT INTO finance_external_provider_state(user_key,provider,state_json,updated_at) VALUES(?,?,?,datetime('now')) ON CONFLICT(user_key,provider) DO UPDATE SET state_json=excluded.state_json,updated_at=datetime('now')`).bind(key,provider,JSON.stringify(state||{})).run()}
async function json(r){const raw=await r.text();let d={};try{d=raw?JSON.parse(raw):{}}catch{}if(!r.ok&&r.status!==202){const e=new Error(clean(d?.errorMessage||d?.Message||d?.message||raw||('Provider request failed ('+r.status+').'),350));e.status=r.status;throw e}return{status:r.status,data:d}}
async function yToken(env,loginName){const form=new URLSearchParams({clientId:env.YODLEE_CLIENT_ID,secret:env.YODLEE_SECRET});const r=await fetch(yBase(env)+'/auth/token',{method:'POST',headers:{'Api-Version':'1.1','Content-Type':'application/x-www-form-urlencoded',loginName},body:form});const x=await json(r),t=clean(x.data?.token?.accessToken,4000);if(!t)throw new Error('Yodlee did not return an access token.');return t}
async function yGet(env,t,ep){return (await json(await fetch(yBase(env)+ep,{headers:{'Api-Version':'1.1',Authorization:'Bearer '+t,Accept:'application/json'}}))).data}
function yMapAccount(a){const id=clean(a?.id,120),pid=clean(a?.providerAccountId,120);return{accountId:'yodlee:'+id,itemId:'yodlee:'+pid,name:clean(a?.accountName||a?.name||a?.accountType||'Account',180),officialName:clean(a?.accountName||'',180),mask:clean(a?.accountNumber||'',80).replace(/\D/g,'').slice(-4),type:clean(a?.container||'bank',80).toLowerCase(),subtype:clean(a?.accountType||'',100).toLowerCase(),currency:clean(a?.balance?.currency||a?.currentBalance?.currency||'CAD',10).toUpperCase(),currentBalance:num(a?.balance?.amount??a?.balance??a?.currentBalance?.amount),availableBalance:num(a?.availableBalance?.amount??a?.availableBalance),creditLimit:num(a?.creditLimit?.amount??a?.creditLimit),updatedAt:clean(a?.lastUpdated||a?.lastRefreshed,80)||new Date().toISOString()}}
function yCat(tx){const t=clean(tx?.categoryType,60).toUpperCase();if(t==='INCOME')return'INCOME';if(t==='TRANSFER')return'TRANSFER_OUT';return clean(tx?.category||'OTHER',100).toUpperCase().replace(/[^A-Z0-9]+/g,'_')}
async function ySync(env,identity){const key=await userKey(env,identity),login='questlog_'+key.replace(/[^a-zA-Z0-9_-]/g,'').slice(0,80),t=await yToken(env,login),[p,a]=await Promise.all([yGet(env,t,'/providerAccounts'),yGet(env,t,'/accounts')]);const rawA=Array.isArray(a?.account)?a.account:[],map=new Map(rawA.map(x=>[clean(x.id,120),yMapAccount(x)])),from=new Date(Date.now()-400*86400000).toISOString().slice(0,10),to=new Date().toISOString().slice(0,10),rawT=[];for(let skip=0;skip<1500;skip+=500){const page=await yGet(env,t,'/transactions?fromDate='+from+'&toDate='+to+'&top=500&skip='+skip),rows=Array.isArray(page?.transaction)?page.transaction:[];rawT.push(...rows);if(rows.length<500)break}const now=new Date().toISOString(),connections=(Array.isArray(p?.providerAccount)?p.providerAccount:[]).map(x=>{const s=clean(x?.status||x?.refreshInfo?.status,80).toUpperCase();return{itemId:'yodlee:'+clean(x?.id,120),institutionId:clean(x?.providerId,120),institutionName:clean(x?.providerName||'Yodlee connection',180),status:s==='USER_INPUT_REQUIRED'?'user_action_required':s==='FAILED'?'error':'connected',error:s==='FAILED'?'Yodlee could not refresh this connection.':'',lastSyncedAt:clean(x?.lastUpdated||x?.lastUpdateAttempt||x?.refreshInfo?.lastRefreshed,80)||now,connectedAt:clean(x?.createdDate,80)||now,provider:'yodlee',providerName:'Yodlee'}});const transactions=rawT.map(tx=>{const aid=clean(tx?.accountId,120),ac=map.get(aid),base=clean(tx?.baseType,20).toUpperCase(),amt=Math.abs(num(tx?.amount?.amount??tx?.amount)||0);return{transactionId:'yodlee:'+clean(tx?.id,160),itemId:ac?.itemId||'',accountId:'yodlee:'+aid,name:clean(tx?.merchant?.name||tx?.description?.simple||tx?.description?.original||tx?.description||'Transaction',220),merchantName:clean(tx?.merchant?.name||'',180),amount:base==='CREDIT'?-amt:amt,currency:clean(tx?.amount?.currency||ac?.currency||'CAD',10).toUpperCase(),date:clean(tx?.transactionDate||tx?.date||tx?.postDate,30).slice(0,10),authorizedDate:clean(tx?.transactionDate,30).slice(0,10),pending:clean(tx?.status,20).toUpperCase()==='PENDING',categoryPrimary:yCat(tx),categoryDetailed:clean(tx?.category||'',120),paymentChannel:'',website:clean(tx?.merchant?.website||'',300),logoUrl:'',provider:'yodlee'}});const old=await getState(env,key,'yodlee'),excluded=new Set(old.excluded||[]),state={connections:connections.filter(x=>!excluded.has(x.itemId)),accounts:[...map.values()].filter(x=>!excluded.has(x.itemId)),transactions:transactions.filter(x=>!excluded.has(x.itemId)),excluded:[...excluded],lastSyncedAt:now};await putState(env,key,'yodlee',state);return state}
async function fToken(env){const r=await fetch(fBase(env)+'/GenerateAuthorizeToken',{method:'POST',headers:{'Content-Type':'application/json','flinks-auth-key':env.FLINKS_AUTH_KEY}}),x=await json(r);return clean(x.data?.AuthorizeToken||x.data?.authorizeToken||x.data?.Token||x.data?.token,4000)}
async function fAuthorize(env,loginId){const token=await fToken(env),r=await fetch(fBase(env)+'/Authorize',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({LoginId:loginId,MostRecentCached:true,Save:true,AuthorizeToken:token})}),x=await json(r),id=clean(x.data?.RequestId||x.data?.requestId,200);if(!id)throw new Error('Flinks did not return a requestId.');return id}
async function fDetail(env,id){let x=await json(await fetch(fBase(env)+'/GetAccountsDetail',{method:'POST',headers:{'Content-Type':'application/json','x-api-key':env.FLINKS_API_KEY},body:JSON.stringify({RequestId:id})}));if(x.status===202){for(let i=0;i<8;i++){await new Promise(r=>setTimeout(r,2000));x=await json(await fetch(fBase(env)+'/GetAccountsDetailAsync?requestId='+encodeURIComponent(id),{headers:{'x-api-key':env.FLINKS_API_KEY}}));if(x.status!==202)break}}if(x.status===202)throw new Error('Flinks is still processing this account. Try Sync again shortly.');return x.data}
function fMap(loginId,p){const now=new Date().toISOString(),item='flinks:'+loginId,currDefault='CAD',accounts=[],transactions=[];for(const a of Array.isArray(p?.Accounts)?p.Accounts:[]){const aid=clean(a?.Id||a?.id,160),curr=clean(a?.Currency||currDefault,10).toUpperCase();accounts.push({accountId:'flinks:'+aid,itemId:item,name:clean(a?.Title||a?.Name||a?.AccountType||'Account',180),officialName:clean(a?.Title||'',180),mask:clean(a?.AccountNumber||'',80).replace(/\D/g,'').slice(-4),type:'depository',subtype:clean(a?.AccountType||a?.Category||'',100).toLowerCase(),currency:curr,currentBalance:num(a?.Balance?.Current??a?.Balance?.Available??a?.Balance),availableBalance:num(a?.Balance?.Available??a?.AvailableBalance),creditLimit:num(a?.CreditLimit),updatedAt:now,provider:'flinks'});for(const t of Array.isArray(a?.Transactions)?a.Transactions:[]){const debit=num(t?.Debit)||0,credit=num(t?.Credit)||0;transactions.push({transactionId:'flinks:'+clean(t?.Id||[aid,t?.Date,t?.Description,debit,credit].join('|'),220),itemId:item,accountId:'flinks:'+aid,name:clean(t?.Description||'Transaction',220),merchantName:clean(t?.MerchantName||'',180),amount:debit>0?debit:-Math.abs(credit),currency:curr,date:clean(t?.Date,30).slice(0,10),authorizedDate:'',pending:false,categoryPrimary:clean(t?.Category||'OTHER',100).toUpperCase().replace(/[^A-Z0-9]+/g,'_'),categoryDetailed:clean(t?.Category||'',120),paymentChannel:'',website:'',logoUrl:'',provider:'flinks'})}}return{connection:{itemId:item,loginId,institutionId:clean(p?.InstitutionId,100),institutionName:clean(p?.Institution||'Flinks connection',180),status:'connected',error:'',lastSyncedAt:clean(p?.Login?.LastRefresh,80)||now,connectedAt:now,provider:'flinks',providerName:'Flinks'},accounts,transactions}}
async function fSyncLogin(env,identity,loginId,institution=''){const key=await userKey(env,identity),old=await getState(env,key,'flinks'),req=await fAuthorize(env,loginId),payload=await fDetail(env,req),mapped=fMap(loginId,payload);if(institution&&!mapped.connection.institutionName)mapped.connection.institutionName=institution;const prev=(old.connections||[]).find(x=>x.loginId===loginId);mapped.connection.connectedAt=prev?.connectedAt||mapped.connection.connectedAt;const state={connections:(old.connections||[]).filter(x=>x.loginId!==loginId).concat(mapped.connection),accounts:(old.accounts||[]).filter(x=>x.itemId!=='flinks:'+loginId).concat(mapped.accounts),transactions:(old.transactions||[]).filter(x=>x.itemId!=='flinks:'+loginId).concat(mapped.transactions),lastSyncedAt:new Date().toISOString()};await putState(env,key,'flinks',state);return state}
export function externalProviders(env){return[{id:'yodlee',name:'Yodlee',configured:yodleeConfigured(env),environment:/sandbox/i.test(yBase(env))?'sandbox':'production'},{id:'flinks',name:'Flinks',configured:flinksConfigured(env),environment:/toolbox|sandbox/i.test(fBase(env)||env.FLINKS_IFRAME_URL)?'sandbox':'production'}]}
export async function startExternalFinance(env,identity,provider,payload={}){const key=await userKey(env,identity);if(provider==='yodlee'){if(!yodleeConfigured(env))throw Object.assign(new Error('Yodlee is not configured.'),{status:503});const login='questlog_'+key.replace(/[^a-zA-Z0-9_-]/g,'').slice(0,80),token=await yToken(env,login),pid=clean(payload.itemId,160).replace(/^yodlee:/,'');return{provider:'yodlee',launch:'yodlee',fastLinkURL:env.YODLEE_FASTLINK_URL,accessToken:'Bearer '+token,params:{configName:env.YODLEE_FASTLINK_CONFIG_NAME,...(pid?{providerAccountId:Number(pid)||pid,flow:'refresh'}:{})}}}if(provider==='flinks'){if(!flinksConfigured(env))throw Object.assign(new Error('Flinks is not configured.'),{status:503});const token=await fToken(env),u=new URL(env.FLINKS_IFRAME_URL),login=clean(payload.itemId,200).replace(/^flinks:/,'');u.searchParams.set('authorizeToken',token);u.searchParams.set('redirectUrl',payload.redirectUri||env.FLINKS_REDIRECT_URL||'about:blank');u.searchParams.set('accountSelectorEnable','true');if(login){u.searchParams.set('loginId',login);u.searchParams.set('reconnect','true')}return{provider:'flinks',launch:'iframe',url:u.toString()}}throw Object.assign(new Error('Unknown finance provider.'),{status:400})}
export async function completeExternalFinance(env,identity,provider,payload={}){if(provider==='yodlee')return ySync(env,identity);if(provider==='flinks'){const id=clean(payload.loginId,200);if(!id)throw Object.assign(new Error('Flinks loginId is required.'),{status:400});return fSyncLogin(env,identity,id,payload.institution||'')}throw Object.assign(new Error('Unknown finance provider.'),{status:400})}
export async function syncExternalFinance(env,identity){const errors=[];if(yodleeConfigured(env)){try{await ySync(env,identity)}catch(e){errors.push({provider:'yodlee',error:clean(e.message,300)})}}if(flinksConfigured(env)){const key=await userKey(env,identity),s=await getState(env,key,'flinks');for(const c of s.connections||[]){try{await fSyncLogin(env,identity,c.loginId)}catch(e){errors.push({provider:'flinks',itemId:c.itemId,error:clean(e.message,300)})}}}return errors}
export async function disconnectExternalFinance(env,identity,itemId){const key=await userKey(env,identity),id=clean(itemId,200),provider=id.split(':')[0];if(provider==='flinks'){const login=id.replace(/^flinks:/,''),s=await getState(env,key,'flinks');s.connections=(s.connections||[]).filter(x=>x.loginId!==login);s.accounts=(s.accounts||[]).filter(x=>x.itemId!==id);s.transactions=(s.transactions||[]).filter(x=>x.itemId!==id);await putState(env,key,'flinks',s);return{ok:true}}if(provider==='yodlee'){const s=await getState(env,key,'yodlee'),excluded=new Set(s.excluded||[]);excluded.add(id);s.excluded=[...excluded];s.connections=(s.connections||[]).filter(x=>x.itemId!==id);s.accounts=(s.accounts||[]).filter(x=>x.itemId!==id);s.transactions=(s.transactions||[]).filter(x=>x.itemId!==id);await putState(env,key,'yodlee',s);return{ok:true}}throw Object.assign(new Error('Unknown finance provider.'),{status:400})}
export async function externalFinanceSummary(env,identity,{sync=false}={}){const key=await userKey(env,identity),errors=sync?await syncExternalFinance(env,identity):[],ys=await getState(env,key,'yodlee'),fs=await getState(env,key,'flinks');return{connections:[...(ys.connections||[]),...(fs.connections||[])],accounts:[...(ys.accounts||[]),...(fs.accounts||[])],transactions:[...(ys.transactions||[]),...(fs.transactions||[])].sort((a,b)=>String(b.date||'').localeCompare(String(a.date||''))).slice(0,1500),errors,lastSyncedAt:[ys.lastSyncedAt,fs.lastSyncedAt].filter(Boolean).sort().at(-1)||null}}
